ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "endPdpUrl" TEXT;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "cms" TEXT;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "remarks" TEXT;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "contactPersons" JSONB;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "leadOwners" JSONB;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "linkedProfiles" JSONB;
