import { useEffect, useMemo, useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import api from '../api/client'
import { useAuth } from '../context/AuthContext'
import RichTextEditor from '../components/RichTextEditor'
import { ArrowLeft, Mail, Building2, Briefcase, ChevronDown, Save, Eye, FlaskConical, Clock3, Send, CheckCircle2, AlertCircle, X, FileText, Wand2, CalendarClock } from 'lucide-react'
import '../styles/single-mail-outreach.css'

const VARIABLES = [
  { label:'First Name', token:'{{first_name}}' }, { label:'Last Name', token:'{{last_name}}' },
  { label:'Company Name', token:'{{company_name}}' }, { label:'Job Title', token:'{{job_title}}' },
  { label:'Sender Name', token:'{{sender_name}}' },
]
const TEMPLATES = [
  { name:'Thoughtful introduction', subject:'A quick idea for {{company_name}}', body:'<p>Hi {{first_name}},</p><p>I noticed your work as {{job_title}} at {{company_name}} and wanted to share an idea that may be relevant to your team.</p><p>Would you be open to a brief conversation next week?</p><p>Best,<br>{{sender_name}}</p>' },
  { name:'Value-led follow-up', subject:'Following up — {{company_name}}', body:'<p>Hi {{first_name}},</p><p>I wanted to follow up with a concise view of how we can support {{company_name}}. I would be happy to tailor this around your current priorities.</p><p>Would a 15-minute conversation be useful?</p><p>Regards,<br>{{sender_name}}</p>' },
  { name:'Meeting request', subject:'15 minutes to discuss {{company_name}}?', body:'<p>Hi {{first_name}},</p><p>Given your role as {{job_title}}, I thought this may be worth a short conversation. I can share the key points in 15 minutes and you can decide if it is relevant.</p><p>Best,<br>{{sender_name}}</p>' },
]
const resolve = (text, p, user) => (text || '').replaceAll('{{first_name}}',p?.firstName||'').replaceAll('{{last_name}}',p?.lastName||'').replaceAll('{{company_name}}',p?.companyName||'').replaceAll('{{job_title}}',p?.jobTitle||'').replaceAll('{{sender_name}}',user?.name||'')

export default function SingleMailOutreach(){
  const navigate=useNavigate(), {user}=useAuth(), [params]=useSearchParams(), id=params.get('prospect')
  const [prospect,setProspect]=useState(null), [gmail,setGmail]=useState({connected:false,email:null}), [loading,setLoading]=useState(true)
  const [subject,setSubject]=useState(''), [body,setBody]=useState(''), [activeField,setActiveField]=useState('body')
  const [preview,setPreview]=useState(false), [templates,setTemplates]=useState(false), [confirm,setConfirm]=useState(false), [schedule,setSchedule]=useState(false), [scheduledAt,setScheduledAt]=useState('')
  const [sending,setSending]=useState(false), [error,setError]=useState(''), [notice,setNotice]=useState(''), [success,setSuccess]=useState(false)
  useEffect(()=>{ if(!id){setLoading(false);return} ; Promise.all([api.get(`/prospects/${id}`),api.get('/email/status'),api.get(`/prospects/${id}/draft`)]).then(([p,g,d])=>{setProspect(p.data);setGmail(g.data);if(d.data){setSubject(d.data.subject||'');setBody(d.data.htmlBody||'')}}).catch(e=>setError(e.response?.data?.message||'Unable to load recipient.')).finally(()=>setLoading(false)) },[id])
  const resolvedSubject=useMemo(()=>resolve(subject,prospect,user),[subject,prospect,user]), resolvedBody=useMemo(()=>resolve(body,prospect,user),[body,prospect,user])
  const insertVariable=token=>{ if(activeField==='subject')setSubject(v=>v+token);else setBody(v=>`${v}${token}`) }
  const flash=m=>{setNotice(m);setTimeout(()=>setNotice(''),2400)}
  const validate=()=>{ if(!prospect?.email)return 'Recipient does not have an email address.';if(!subject.trim())return 'Subject is required.';if(!body.replace(/<[^>]*>/g,'').trim())return 'Email body is required.';return '' }
  const saveDraft=async()=>{const issue=validate().replace('Email body is required.','');if(issue&&issue!=='Subject is required.')return setError(issue);await api.put(`/prospects/${id}/draft`,{subject,htmlBody:body});flash('Draft saved.')}
  const send=async(to=prospect?.email,isTest=false)=>{const issue=validate();if(issue)return setError(issue);if(!gmail.connected)return setError('Connect Gmail in Settings before sending.');setSending(true);setError('');try{await api.post('/email/send',{to,subject:resolvedSubject,htmlBody:resolvedBody,emailMode:'new'});if(!isTest){await api.post(`/prospects/${id}/email-sent`,{subject:resolvedSubject});setSuccess(true)}else flash(`Test email sent to ${to}.`);setConfirm(false)}catch(e){setError(e.response?.data?.message||'Email could not be sent.')}finally{setSending(false)}}
  const sendTest=()=>{const email=window.prompt('Send test email to:',user?.email||gmail.email||'');if(email)send(email,true)}
  const doSchedule=async()=>{const issue=validate();if(issue)return setError(issue);try{await api.post(`/prospects/${id}/schedule`,{toEmail:prospect.email,subject:resolvedSubject,htmlBody:resolvedBody,scheduledAt});setSchedule(false);flash('Email scheduled and activity recorded.')}catch(e){setError(e.response?.data?.message||'Unable to schedule email.')}}
  if(loading)return <div className="sm-state"><span className="sm-spinner"/><h2>Loading composer</h2></div>
  if(!prospect)return <div className="sm-state"><AlertCircle/><h2>Select a prospect first</h2><p>Open the Prospect &amp; Channel Board and choose Email Outreach.</p><button onClick={()=>navigate('/prospects')}>Go to prospect board</button></div>
  if(success)return <Success prospect={prospect} onContact={()=>navigate(`/prospects?view=${id}`)} onAnother={()=>{setSuccess(false);setSubject('');setBody('')}} onReturn={()=>navigate('/prospects')}/>
  return <div className="sm-page">
    <header className="sm-page-head"><button onClick={()=>navigate(`/prospects?view=${id}`)}><ArrowLeft/>Prospect profile</button><div><span>Outreach</span><h1>Single Mail</h1><p>Personalized one-to-one email</p></div><div className={`sm-account ${gmail.connected?'connected':'warning'}`}><i/ ><span>Sending account<strong>{gmail.email||'Gmail not connected'}</strong></span></div></header>
    <section className="sm-recipient"><div className="sm-avatar">{`${prospect.firstName?.[0]||''}${prospect.lastName?.[0]||''}`}</div><div className="sm-recipient-name"><span>Recipient</span><strong>{prospect.firstName} {prospect.lastName}</strong></div><div><Building2/><span>Company<strong>{prospect.companyName||'Not provided'}</strong></span></div><div><Briefcase/><span>Job title<strong>{prospect.jobTitle||'Not provided'}</strong></span></div><div><Mail/><span>Email address<strong>{prospect.email||'Missing email'}</strong></span></div></section>
    <div className="sm-workspace"><main className="sm-composer"><div className="sm-composer-head"><div><h2>Email message</h2><p>Variables resolve automatically for this recipient.</p></div><button onClick={()=>setTemplates(true)}><FileText/>Choose template<ChevronDown/></button></div><div className="sm-fields"><label><span>From</span><input value={gmail.email||user?.email||''} readOnly/><em>{gmail.connected?'Connected':'Not connected'}</em></label><label><span>To</span><input value={`${prospect.firstName} ${prospect.lastName} <${prospect.email||''}>`} readOnly/></label><label><span>Subject</span><input value={subject} onFocus={()=>setActiveField('subject')} onChange={e=>setSubject(e.target.value)} placeholder="A concise, relevant subject"/><small>{resolvedSubject&&resolvedSubject!==subject?`Preview: ${resolvedSubject}`:''}</small></label><div className="sm-body-field" onMouseDown={()=>setActiveField('body')}><span>Email body</span><RichTextEditor value={body} onChange={setBody} minHeight={270} placeholder="Write a personal, useful message…"/></div></div></main><aside className="sm-personalize"><div className="sm-aside-head"><Wand2/><div><h3>Personalization</h3><p>Insert into subject or body</p></div></div><div className="sm-variable-list">{VARIABLES.map(v=><button key={v.token} onClick={()=>insertVariable(v.token)}><span>{v.label}</span><code>{v.token}</code></button>)}</div><div className="sm-resolved"><span>Recipient values</span>{VARIABLES.map(v=><div key={v.token}><small>{v.label}</small><strong>{resolve(v.token,prospect,user)||'Not available'}</strong></div>)}</div></aside></div>
    {error&&<div className="sm-error"><AlertCircle/><span>{error}</span><button onClick={()=>setError('')}><X/></button></div>}
    <footer className="sm-actionbar"><div><button onClick={saveDraft}><Save/>Save as draft</button><button onClick={()=>setPreview(true)}><Eye/>Preview email</button><button onClick={sendTest}><FlaskConical/>Send test email</button><button onClick={()=>setSchedule(true)}><Clock3/>Schedule send</button></div><button className="primary" onClick={()=>{const issue=validate();issue?setError(issue):setConfirm(true)}}><Send/>Send email</button></footer>
    {preview&&<Preview prospect={prospect} from={gmail.email||user?.email} subject={resolvedSubject} body={resolvedBody} onClose={()=>setPreview(false)}/>} 
    {templates&&<TemplateModal onClose={()=>setTemplates(false)} onChoose={t=>{setSubject(t.subject);setBody(t.body);setTemplates(false)}}/>}
    {confirm&&<Confirm prospect={prospect} subject={resolvedSubject} from={gmail.email||user?.email} sending={sending} onClose={()=>setConfirm(false)} onSend={()=>send()}/>} 
    {schedule&&<Schedule value={scheduledAt} onChange={setScheduledAt} onClose={()=>setSchedule(false)} onSchedule={doSchedule}/>} 
    {notice&&<div className="sm-toast"><CheckCircle2/>{notice}</div>}
  </div>
}

function Preview({prospect,from,subject,body,onClose}){return <div className="sm-overlay"><div className="sm-preview"><header><div><Eye/><span>Recipient preview<strong>Exactly as {prospect.firstName} will see it</strong></span></div><button onClick={onClose}><X/></button></header><div className="sm-preview-meta"><div><span>From</span><strong>{from}</strong></div><div><span>To</span><strong>{prospect.firstName} {prospect.lastName} &lt;{prospect.email}&gt;</strong></div><div><span>Subject</span><strong>{subject}</strong></div></div><article dangerouslySetInnerHTML={{__html:body}}/><footer><button onClick={onClose}>Close preview</button></footer></div></div>}
function TemplateModal({onClose,onChoose}){return <div className="sm-overlay"><div className="sm-dialog"><header><div><FileText/><span>Choose template<strong>Start with a concise B2B structure</strong></span></div><button onClick={onClose}><X/></button></header><div className="sm-template-list">{TEMPLATES.map(t=><button key={t.name} onClick={()=>onChoose(t)}><span><strong>{t.name}</strong><small>{t.subject}</small></span><ArrowLeft/></button>)}</div></div></div>}
function Confirm({prospect,subject,from,sending,onClose,onSend}){return <div className="sm-overlay"><div className="sm-dialog sm-confirm"><header><div><Send/><span>Send this email?<strong>One final check before delivery</strong></span></div><button onClick={onClose}><X/></button></header><div><dl><dt>Recipient</dt><dd>{prospect.firstName} {prospect.lastName} · {prospect.email}</dd><dt>Subject</dt><dd>{subject}</dd><dt>Sending account</dt><dd>{from}</dd></dl><p><CheckCircle2/>The contact status will update to Contacted and this email will be recorded in activity history.</p></div><footer><button onClick={onClose}>Cancel</button><button className="primary" onClick={onSend} disabled={sending}>{sending?'Sending…':'Confirm & send'}</button></footer></div></div>}
function Schedule({value,onChange,onClose,onSchedule}){return <div className="sm-overlay"><div className="sm-dialog sm-schedule"><header><div><CalendarClock/><span>Schedule send<strong>Choose a future local date and time</strong></span></div><button onClick={onClose}><X/></button></header><div><label>Send date and time<input type="datetime-local" value={value} min={new Date(Date.now()+300000).toISOString().slice(0,16)} onChange={e=>onChange(e.target.value)}/></label></div><footer><button onClick={onClose}>Cancel</button><button className="primary" onClick={onSchedule}>Schedule email</button></footer></div></div>}
function Success({prospect,onContact,onAnother,onReturn}){return <div className="sm-success"><span><CheckCircle2/></span><h1>Email sent successfully</h1><p>Your message was delivered to <strong>{prospect.firstName} {prospect.lastName}</strong>. Their status is now Contacted and the activity timeline has been updated.</p><div><button onClick={onContact}>View contact</button><button onClick={onAnother}>Send another email</button><button className="primary" onClick={onReturn}>Return to outreach</button></div></div>}
