import { useEffect, useMemo, useRef, useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import api from '../api/client'
import { useAuth } from '../context/AuthContext'
import RichTextEditor from '../components/RichTextEditor'
import { AlertCircle, ArrowLeft, ArrowRight, BarChart3, CalendarClock, Check, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, Clock3, Copy, Download, ExternalLink, Eye, File, FileSpreadsheet, FileText, Globe2, Image, Library, Linkedin, Mail, MessageSquare, Paperclip, Plus, Save, Send, Sparkles, Upload, Wand2, X, Zap } from 'lucide-react'
import '../styles/single-mail-outreach.css'

const EMAIL_RX=/^[^\s@]+@[^\s@]+\.[^\s@]+$/
const TONES=['Professional','Friendly','Concise','Consultative','Executive']
const VARIABLES=[['First Name','{{First Name}}'],['Company Name','{{Company Name}}'],['Job Title','{{Job Title}}'],['Country','{{Country}}'],['Sender Name','{{Sender Name}}'],['Client Company','{{Client Company}}']]
const TEMPLATES=[
 ['Company Introduction','Introducing NXT Sales to {{Company Name}}','<p>Hi {{First Name}},</p><p>I’m reaching out because your work as {{Job Title}} at {{Company Name}} stood out to us. We help commercial teams turn product and customer data into clearer sales opportunities.</p><p>Would you be open to a brief introduction next week?</p>'],
 ['Product Introduction','A practical idea for {{Company Name}}','<p>Hi {{First Name}},</p><p>I wanted to share a practical way we could support {{Company Name}} with stronger product data and digital commerce operations.</p><p>Could we explore this in a focused 20-minute call?</p>'],
 ['Partnership Opportunity','Partnership opportunity with {{Company Name}}','<p>Hi {{First Name}},</p><p>I see a strong potential fit between our teams and would value the opportunity to explore a partnership with {{Company Name}}.</p><p>Would next week suit a short discussion?</p>'],
 ['Meeting Request','20 minutes with {{Company Name}}?','<p>Hi {{First Name}},</p><p>Given your role as {{Job Title}}, I thought a short discussion about your current priorities may be useful.</p><p>Would Tuesday or Wednesday work for 20 minutes?</p>'],
 ['Catalogue Sharing','Product catalogue for {{Company Name}}','<p>Hi {{First Name}},</p><p>I’ve attached our product catalogue for your review. I selected the sections most relevant to {{Company Name}}.</p><p>Which area would be most useful to discuss?</p>'],
 ['Proposal Sharing','Proposal for {{Company Name}}','<p>Hi {{First Name}},</p><p>Please find our proposal attached. It reflects the priorities discussed and outlines the recommended next steps.</p><p>I’m happy to walk you through it this week.</p>'],
 ['Follow-up','Following up — {{Company Name}}','<p>Hi {{First Name}},</p><p>I wanted to follow up on my previous note in case it was buried. Is this a priority your team is considering this quarter?</p><p>Happy to keep the conversation brief.</p>'],
 ['Thank You','Thank you, {{First Name}}','<p>Hi {{First Name}},</p><p>Thank you for your time today. I appreciated the context you shared about {{Company Name}} and will follow up with the agreed information.</p>'],['Custom','','']]
const LIBRARY=[
 {id:'profile',name:'NXT Company Profile.pdf',type:'Company Profile',mimeType:'application/pdf',size:'2.4 MB'},
 {id:'catalogue',name:'Digital Commerce Catalogue.pdf',type:'Product Catalogue',mimeType:'application/pdf',size:'4.8 MB'},
 {id:'brochure',name:'Product Data Services.pdf',type:'Product Brochure',mimeType:'application/pdf',size:'1.7 MB'},
 {id:'case',name:'B2B Commerce Case Study.pdf',type:'Case Study',mimeType:'application/pdf',size:'1.1 MB'},
 {id:'proposal',name:'Proposal Template.docx',type:'Proposal',mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',size:'620 KB'},
 {id:'pricing',name:'Service Pricing.xlsx',type:'Pricing Sheet',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',size:'340 KB'},
 {id:'data',name:'Integration Datasheet.pdf',type:'Technical Datasheet',mimeType:'application/pdf',size:'980 KB'}]
const strip=v=>String(v||'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim()
const fmtDate=v=>v?new Intl.DateTimeFormat('en',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(v)):'Never'
const resolve=(text,p,user)=>String(text||'').replaceAll('{{First Name}}',p?.firstName||'').replaceAll('{{Company Name}}',p?.companyName||'').replaceAll('{{Job Title}}',p?.jobTitle||'').replaceAll('{{Country}}',p?.country||'').replaceAll('{{Sender Name}}',user?.name||'').replaceAll('{{Client Company}}','NXT Sales').replaceAll('{{first_name}}',p?.firstName||'').replaceAll('{{company_name}}',p?.companyName||'').replaceAll('{{job_title}}',p?.jobTitle||'').replaceAll('{{sender_name}}',user?.name||'')
function contextualDraft(p,user,tone='Professional',follow=false){const intro=follow?'I wanted to follow up on my previous note':`I noticed your work as ${p.jobTitle||'a business leader'} at ${p.companyName||'your company'}`;const line=tone==='Friendly'?'I thought this might be useful for your team.':tone==='Executive'?'The opportunity is to reduce operational friction while improving commercial readiness.':tone==='Consultative'?'I would value understanding how your team currently manages product information and commercial readiness.':'We help B2B teams improve product data, digital commerce operations, and sales readiness.';return{subject:follow?`Following up — ${p.companyName||'our conversation'}`:`${p.companyName||'Your team'}: a practical commerce opportunity`,body:`<p>Hi ${p.firstName||'there'},</p><p>${intro}. ${line}</p><p>Would you be open to a focused 20-minute conversation next week?</p><p>Best regards,<br>${user?.name||'NXT Sales'}</p>`}}

export default function SingleMailOutreach(){
 const navigate=useNavigate(),{user}=useAuth(),[params]=useSearchParams(),id=params.get('prospect'),fileRef=useRef(null)
 const [prospect,setProspect]=useState(null),[prospects,setProspects]=useState([]),[gmail,setGmail]=useState({connected:false}),[loading,setLoading]=useState(true)
 const [channel,setChannel]=useState('Email'),[subject,setSubject]=useState(''),[body,setBody]=useState(''),[signature,setSignature]=useState(''),[to,setTo]=useState([]),[cc,setCc]=useState([]),[bcc,setBcc]=useState([]),[copies,setCopies]=useState(false),[activeField,setActiveField]=useState('body')
 const [tone,setTone]=useState('Professional'),[rightTab,setRightTab]=useState('ai'),[rightOpen,setRightOpen]=useState(true),[aiBusy,setAiBusy]=useState(false),[suggestion,setSuggestion]=useState(null),[attachments,setAttachments]=useState([])
 const [assetModal,setAssetModal]=useState(false),[templateOpen,setTemplateOpen]=useState(false),[preview,setPreview]=useState(false),[confirm,setConfirm]=useState(false),[schedule,setSchedule]=useState(false),[scheduledAt,setScheduledAt]=useState(''),[timezone,setTimezone]=useState(Intl.DateTimeFormat().resolvedOptions().timeZone)
 const [sending,setSending]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[success,setSuccess]=useState(false),[followDays,setFollowDays]=useState('3')
 useEffect(()=>{if(!id){navigate('/prospects?compose=single-mail',{replace:true});return}Promise.all([api.get(`/prospects/${id}`),api.get('/prospects?limit=100'),api.get('/email/status'),api.get(`/prospects/${id}/draft`)]).then(([p,all,g,d])=>{setProspect(p.data);setProspects(all.data.prospects||[]);setGmail(g.data);setTo(p.data.email?[p.data.email]:[]);if(d.data){setSubject(d.data.subject||'');setBody(d.data.htmlBody||'')}}).catch(e=>setError(e.response?.data?.message||'Unable to load outreach workspace.')).finally(()=>setLoading(false))},[id,navigate])
 const resolvedSubject=useMemo(()=>resolve(subject,prospect,user),[subject,prospect,user]),resolvedBody=useMemo(()=>resolve(body,prospect,user),[body,prospect,user])
 const score=useMemo(()=>Math.min(100,25+(prospect?.firstName?15:0)+(prospect?.companyName?15:0)+(prospect?.jobTitle?10:0)+(subject.trim()?10:0)+(strip(body).length>80?15:0)+(/\?|call|meeting|reply/i.test(strip(body))?10:0)),[prospect,subject,body])
 const missing=useMemo(()=>[!prospect?.jobTitle&&'job title',!prospect?.country&&'country',!subject.trim()&&'specific subject',strip(body).length<80&&'context-rich message',!/\?|call|meeting|reply/i.test(strip(body))&&'clear CTA'].filter(Boolean),[prospect,subject,body])
 const smartAsset=useMemo(()=>/technical|engineer|data|IT/i.test(`${prospect?.jobTitle} ${body}`)?LIBRARY[6]:/catalog|product/i.test(`${subject} ${body}`)?LIBRARY[2]:LIBRARY[0],[prospect,subject,body])
 const flash=m=>{setNotice(m);setTimeout(()=>setNotice(''),2600)},emailsValid=list=>list.every(x=>EMAIL_RX.test(x))
 const validate=()=>!to.length?'Add at least one recipient.':!emailsValid([...to,...cc,...bcc])?'One or more recipient email addresses are invalid.':!subject.trim()?'Subject is required.':!strip(body)?'Email body is required.':''
 const setRecipients=(setter,value)=>setter(value.split(/[;,\s]+/).map(x=>x.trim()).filter(Boolean))
 const insertVariable=token=>activeField==='subject'?setSubject(v=>v+token):setBody(v=>`${v}${token}`)
 const index=prospects.findIndex(p=>p.id===id),navigateProspect=d=>{const next=prospects[index+d];if(next)navigate(`/outreach/single-mail?prospect=${next.id}`)}
 const saveDraft=async()=>{try{await api.put(`/prospects/${id}/draft`,{subject,htmlBody:body});flash('Draft saved to this prospect.')}catch(e){setError(e.response?.data?.message||'Unable to save draft.')}}
 const fileToAttachment=file=>new Promise((ok,bad)=>{const reader=new FileReader();reader.onload=()=>ok({id:`upload-${Date.now()}-${file.name}`,name:file.name,filename:file.name,type:'Uploaded file',size:`${(file.size/1024/1024).toFixed(2)} MB`,mimeType:file.type||'application/octet-stream',content:String(reader.result).split(',')[1],url:URL.createObjectURL(file)});reader.onerror=bad;reader.readAsDataURL(file)})
 const addFiles=async e=>{const files=[...e.target.files];if(files.some(f=>!/\.(pdf|docx|xlsx|pptx|png|jpe?g|gif|webp)$/i.test(f.name))){setError('Supported files: PDF, DOCX, XLSX, PPTX and images.');return}const items=await Promise.all(files.map(fileToAttachment));setAttachments(v=>[...v,...items]);e.target.value='';flash(`${items.length} file${items.length>1?'s':''} attached.`)}
 const attachAsset=a=>{if(attachments.some(x=>x.id===a.id))return;setAttachments(v=>[...v,{...a,filename:a.name,library:true}]);flash(`${a.name} added. You remain in control of sending.`)}
 const runAI=(action='Generate Email')=>{setAiBusy(true);setTimeout(()=>{let d=contextualDraft(prospect,user,tone,action==='Generate Follow-up');if(action==='Make Shorter')d={subject,body:`<p>Hi ${prospect.firstName},</p><p>${strip(body).split(/[.!?]/).filter(Boolean).slice(0,2).join('. ')}.</p><p>Open to a brief call?</p>`};if(action==='Create Stronger Subject')d={subject:`${prospect.companyName}: ${prospect.jobTitle?'a relevant growth idea':'a practical next step'}`,body};if(action==='Improve CTA')d={subject,body:`${body}<p><strong>Would Tuesday or Wednesday suit a focused 20-minute discussion?</strong></p>`};if(['Fix Grammar','Improve Writing','Make More Professional'].includes(action))d={subject,body:String(body).replace(/\s{2,}/g,' ').replace(/<p>hi/i,'<p>Hi')};setSuggestion({action,...d});setAiBusy(false)},520)}
 const applySuggestion=mode=>{if(mode==='insert')setBody(v=>`${v}${suggestion.body}`);else{setSubject(suggestion.subject);setBody(suggestion.body)}setSuggestion(null);flash('AI suggestion applied to the editable draft.')}
 const send=async(testTo=null)=>{const issue=validate();if(issue)return setError(issue);if(!gmail.connected)return setError('Connect Gmail in Settings before sending.');setSending(true);setError('');try{await api.post('/email/send',{to:testTo||to.join(', '),cc:cc.join(', '),bcc:bcc.join(', '),subject:resolvedSubject,htmlBody:`${resolvedBody}${signature?`<div>${signature}</div>`:''}`,attachments:attachments.filter(a=>a.content).map(a=>({filename:a.filename,mimeType:a.mimeType,content:a.content})),companyId:prospect.companyId||undefined,emailMode:channel==='Follow-up'?'continue':'new'});if(testTo)flash(`Test email sent to ${testTo}.`);else{await api.post(`/prospects/${id}/email-sent`,{subject:resolvedSubject});setSuccess(true)}setConfirm(false)}catch(e){setError(e.response?.data?.message||'Email could not be sent.')}finally{setSending(false)}}
 const sendTest=()=>{const email=window.prompt('Send test email to:',user?.email||gmail.email||'');if(email&&EMAIL_RX.test(email))send(email);else if(email)setError('Enter a valid test email address.')}
 const doSchedule=async()=>{const issue=validate();if(issue)return setError(issue);try{await api.post(`/prospects/${id}/schedule`,{toEmail:to.join(', '),subject:resolvedSubject,htmlBody:resolvedBody,scheduledAt,timezone});setSchedule(false);flash(`Email scheduled in ${timezone}.`)}catch(e){setError(e.response?.data?.message||'Unable to schedule email.')}}
 const followUp=()=>{setChannel('Follow-up');setSuggestion({action:'Generate Follow-up',...contextualDraft(prospect,user,tone,true)});setRightTab('ai');setRightOpen(true)}
 if(loading)return <div className="sm-state"><span className="sm-spinner"/><h2>Loading outreach workspace</h2></div>
 if(!prospect)return <div className="sm-state"><span className="sm-spinner"/><h2>Opening prospect selection</h2><p>Choose a decision maker to start the AI outreach workspace.</p></div>
 if(success)return <Success prospect={prospect} onTimeline={()=>{setSuccess(false);setRightTab('timeline')}} onAnother={()=>{setSuccess(false);setSubject('');setBody('');setAttachments([])}} onReturn={()=>navigate('/prospects')}/>
 return <div className={`sm-page ${rightOpen?'':'right-closed'}`}>
  <header className="sm-top"><div><button className="sm-back" onClick={()=>navigate(`/prospects?view=${id}`)}><ArrowLeft/>Prospects</button><span className="sm-divider"/><div><h1>AI Outreach Workspace</h1><p>Personalized one-to-one engagement</p></div></div><div className={`sm-account ${gmail.connected?'connected':'warning'}`}><i/><span>{gmail.connected?'Sending account connected':'Action required'}<strong>{gmail.email||'Connect Gmail in Settings'}</strong></span></div></header>
  <section className="sm-context"><div className="sm-person"><span className="sm-avatar">{`${prospect.firstName?.[0]||''}${prospect.lastName?.[0]||''}`}</span><div><span>Selected prospect</span><h2>{prospect.firstName} {prospect.lastName}</h2><p>{prospect.jobTitle||'Designation not available'} · {prospect.companyName||'Company not available'}</p></div></div><div className="sm-facts"><span><Globe2/><small>Country</small><strong>{prospect.country||'Not available'}</strong></span><span><Mail/><small>Email</small><strong>{prospect.email||'Missing'}</strong></span><span><Linkedin/><small>LinkedIn</small><strong>{prospect.linkedinUrl?'Profile available':'Not available'}</strong></span><span><BarChart3/><small>Lead status</small><strong className="sm-status">{prospect.status||'New'}</strong></span><span><Clock3/><small>Last contacted</small><strong>{fmtDate(prospect.lastContacted)}</strong></span></div><div className="sm-prospect-nav"><button disabled={index<=0} onClick={()=>navigateProspect(-1)}><ChevronLeft/>Previous</button><span>{index>=0?index+1:'–'} / {prospects.length||'–'}</span><button disabled={index<0||index>=prospects.length-1} onClick={()=>navigateProspect(1)}>Next<ChevronRight/></button></div></section>
  <nav className="sm-channel-tabs">{[['Email',Mail],['LinkedIn',Linkedin],['Follow-up',MessageSquare]].map(([name,Icon])=><button key={name} className={channel===name?'active':''} onClick={()=>name==='Follow-up'?followUp():setChannel(name)}><Icon/>{name}{name==='Email'&&<em>Primary</em>}</button>)}</nav>
  {channel==='LinkedIn'?<LinkedInWorkspace prospect={prospect} tone={tone} onTone={setTone} flash={flash}/>:<div className="sm-main-grid"><main className="sm-composer">
   <div className="sm-card-head"><div><span className="sm-icon blue"><Mail/></span><div><h3>{channel==='Follow-up'?'Follow-up email':'Email composer'}</h3><p>{channel==='Follow-up'?'Continue the previous conversation thread':'Write, personalize, preview and send'}</p></div></div><button onClick={()=>setTemplateOpen(true)}><FileText/>Templates<ChevronDown/></button></div>
   {channel==='Follow-up'&&<div className="sm-thread-note"><MessageSquare/><span><strong>Continuing the existing email thread</strong>AI uses the previous email and activity history.</span><select value={followDays} onChange={e=>setFollowDays(e.target.value)}><option value="2">Follow up in 2 days</option><option value="3">Follow up in 3 days</option><option value="5">Follow up in 5 days</option><option value="7">Follow up in 1 week</option><option value="custom">Custom</option></select></div>}
   <div className="sm-fields"><label className="sm-line"><span>From</span><input value={gmail.email||user?.email||''} readOnly/><em>{gmail.connected?'Connected':'Not connected'}</em></label><label className="sm-line"><span>To</span><input className={emailsValid(to)?'':'invalid'} value={to.join(', ')} onChange={e=>setRecipients(setTo,e.target.value)} placeholder="name@company.com"/><button type="button" onClick={()=>setCopies(v=>!v)}>Cc Bcc</button></label>{copies&&<><label className="sm-line"><span>CC</span><input value={cc.join(', ')} onChange={e=>setRecipients(setCc,e.target.value)} placeholder="Separate emails with commas"/></label><label className="sm-line"><span>BCC</span><input value={bcc.join(', ')} onChange={e=>setRecipients(setBcc,e.target.value)} placeholder="Separate emails with commas"/></label></>}<label className="sm-line"><span>Subject</span><input value={subject} onFocus={()=>setActiveField('subject')} onChange={e=>setSubject(e.target.value)} placeholder="A concise, relevant subject"/><small>{subject.length}/120</small></label><div className="sm-variable-row"><span>Personalize:</span>{VARIABLES.map(([label,token])=><button key={token} onClick={()=>insertVariable(token)} title={`Insert ${label}`}>{token}</button>)}</div><div className="sm-body-field" onMouseDown={()=>setActiveField('body')}><RichTextEditor value={body} onChange={setBody} minHeight={235} placeholder="Write a personal, useful message…"/></div><label className="sm-signature"><span>Signature</span><textarea value={signature} onChange={e=>setSignature(e.target.value)} placeholder={`${user?.name||'Your name'}\nNXT Sales`}/></label></div>
   <section className="sm-attachments"><div className="sm-section-title"><div><Paperclip/><span><strong>Attachments &amp; sales assets</strong><small>{attachments.length} attached · PDF, DOCX, XLSX, PPTX and images</small></span></div><div><button onClick={()=>fileRef.current?.click()}><Upload/>Upload</button><button onClick={()=>setAssetModal(true)}><Library/>Asset library</button><input ref={fileRef} hidden multiple type="file" accept=".pdf,.docx,.xlsx,.pptx,image/*" onChange={addFiles}/></div></div>{attachments.length?<div className="sm-file-list">{attachments.map(a=><FileItem key={a.id} file={a} onRemove={()=>setAttachments(v=>v.filter(x=>x.id!==a.id))}/>)}</div>:<button className="sm-drop" onClick={()=>fileRef.current?.click()}><Upload/><span><strong>Drop files here or browse</strong>Multiple files supported · Max 25 MB each</span></button>}{!attachments.some(a=>a.id===smartAsset.id)&&<div className="sm-smart-asset"><Sparkles/><span><strong>Smart recommendation</strong>{smartAsset.name} fits this prospect context.</span><button onClick={()=>attachAsset(smartAsset)}>Attach</button><button onClick={()=>flash('Recommendation dismissed.')}>Not now</button></div>}</section>
  </main><aside className="sm-right"><div className="sm-right-tabs">{[['ai','AI Assistant',Sparkles],['assets','Assets',Paperclip],['timeline','Timeline',Clock3]].map(([key,label,Icon])=><button key={key} className={rightTab===key?'active':''} onClick={()=>setRightTab(key)}><Icon/>{label}</button>)}<button className="collapse" onClick={()=>setRightOpen(false)}><ChevronRight/></button></div>{rightTab==='ai'&&<AIPanel tone={tone} setTone={setTone} score={score} missing={missing} busy={aiBusy} runAI={runAI}/>} {rightTab==='assets'&&<AssetPanel assets={LIBRARY} attached={attachments} attach={attachAsset}/>} {rightTab==='timeline'&&<Timeline activity={prospect.activities||[]} onFollowUp={followUp}/>}</aside></div>}
  {!rightOpen&&channel!=='LinkedIn'&&<button className="sm-open-ai" onClick={()=>setRightOpen(true)}><Sparkles/>AI Assistant</button>}
  {error&&<div className="sm-error"><AlertCircle/><span>{error}</span><button onClick={()=>setError('')}><X/></button></div>}
  {channel!=='LinkedIn'&&<footer className="sm-actionbar"><div><button onClick={saveDraft}><Save/>Save draft</button><button onClick={()=>setPreview(true)}><Eye/>Preview</button><button onClick={sendTest}><Zap/>Send test</button><button onClick={()=>setSchedule(true)}><CalendarClock/>Schedule</button></div><span className="sm-ready"><CheckCircle2/>Editable outreach draft</span><button className="primary" onClick={()=>{const issue=validate();issue?setError(issue):setConfirm(true)}}><Send/>Send email</button></footer>}
  {suggestion&&<AISuggestion suggestion={suggestion} onClose={()=>setSuggestion(null)} onApply={applySuggestion}/>} {preview&&<Preview from={gmail.email||user?.email} to={to} cc={cc} subject={resolvedSubject} body={resolvedBody} signature={signature} attachments={attachments} onClose={()=>setPreview(false)}/>} {templateOpen&&<TemplateModal onClose={()=>setTemplateOpen(false)} onChoose={t=>{setSubject(t[1]);setBody(t[2]);setTemplateOpen(false);flash(`${t[0]} loaded as an editable draft.`)}}/>} {assetModal&&<AssetModal attached={attachments} attach={attachAsset} onClose={()=>setAssetModal(false)}/>} {confirm&&<Confirm prospect={prospect} subject={resolvedSubject} from={gmail.email||user?.email} attachments={attachments} sending={sending} onClose={()=>setConfirm(false)} onSend={()=>send()}/>} {schedule&&<Schedule value={scheduledAt} timezone={timezone} onTimezone={setTimezone} onChange={setScheduledAt} onClose={()=>setSchedule(false)} onSchedule={doSchedule}/>} {notice&&<div className="sm-toast"><CheckCircle2/>{notice}</div>}
 </div>
}

function AIPanel({tone,setTone,score,missing,busy,runAI}){const actions=['Improve Writing','Make Shorter','Make More Professional','Personalize More','Create Stronger Subject','Improve CTA','Fix Grammar','Change Tone','Rewrite Selected Text','Generate Follow-up'];return <div className="sm-ai-panel"><div className="sm-ai-hero"><span><Sparkles/></span><div><h3>AI writing assistant</h3><p>Uses prospect, company and sender context.</p></div></div><label className="sm-tone">Tone<select value={tone} onChange={e=>setTone(e.target.value)}>{TONES.map(x=><option key={x}>{x}</option>)}</select></label><button className="sm-generate" disabled={busy} onClick={()=>runAI()}><Wand2/>{busy?'Creating suggestion…':'Generate personalized email'}</button><div className="sm-actions-grid">{actions.map(a=><button key={a} onClick={()=>runAI(a)}>{a}</button>)}</div><div className="sm-score"><div><span>Personalization score</span><strong>{score}%</strong></div><i><b style={{width:`${score}%`}}/></i><p>{missing.length?`To improve: add ${missing.slice(0,3).join(', ')}.`:'Strong context, relevance and clear next step detected.'}</p></div><div className="sm-suggestions"><h4><Zap/>Proactive suggestions</h4>{missing.slice(0,4).map((x,i)=><button key={x} onClick={()=>runAI(i?'Improve CTA':'Personalize More')}><span>{i?'Review':'Add'}</span>{x==='clear CTA'?'Add a clearer, time-bound CTA':x==='specific subject'?'Make the subject more specific':x==='context-rich message'?"Mention the prospect's industry and role":`Add the prospect's ${x}`}<ArrowRight/></button>)}</div></div>}
function AssetPanel({assets,attached,attach}){return <div className="sm-asset-panel"><div className="sm-panel-copy"><h3>Sales asset library</h3><p>Choose documents deliberately before sending.</p></div>{assets.map(a=><div className="sm-library-item" key={a.id}><FileIcon type={a.mimeType}/><span><strong>{a.name}</strong><small>{a.type} · {a.size}</small></span><button disabled={attached.some(x=>x.id===a.id)} onClick={()=>attach(a)}>{attached.some(x=>x.id===a.id)?<Check/>:<Plus/>}</button></div>)}</div>}
function Timeline({activity,onFollowUp}){const defaults=['Email Drafted','Email Sent','Delivered','Opened','Link Clicked','Replied','Follow-up Sent'];return <div className="sm-timeline"><div className="sm-panel-copy"><h3>Outreach timeline</h3><p>Delivery events appear when supported by the email system.</p></div>{activity.length?activity.map(a=><div className="sm-event" key={a.id}><i/><span><strong>{a.title}</strong><small>{fmtDate(a.createdAt)}{a.detail?` · ${a.detail}`:''}</small></span></div>):defaults.map((x,i)=><div className={`sm-event ${i?'pending':''}`} key={x}><i/><span><strong>{x}</strong><small>{i?'Waiting for supported event':'Current draft in progress'}</small></span></div>)}<button className="sm-follow" onClick={onFollowUp}><Sparkles/>Generate contextual follow-up</button></div>}
function LinkedInWorkspace({prospect,tone,onTone,flash}){const[kind,setKind]=useState('Connection Request'),[message,setMessage]=useState(`Hi ${prospect.firstName} — I noticed your work at ${prospect.companyName}. We help B2B teams strengthen product data and commerce operations. Open to connecting?`);const revise=mode=>{let v=message;if(mode==='Make Shorter')v=v.split(' ').slice(0,28).join(' ');if(mode==='Make Natural')v=`Hi ${prospect.firstName} — your work at ${prospect.companyName} caught my attention. We help teams improve product data and commerce operations. Worth connecting?`;if(mode==='Personalize')v=`Hi ${prospect.firstName} — given your role as ${prospect.jobTitle||'a leader'} at ${prospect.companyName}, our work may be relevant. Open to connecting?`;if(mode==='Improve CTA')v=`${v.replace(/Open to.*$/,'')} Would a quick 15-minute exchange next week be useful?`;setMessage(v)};return <div className="sm-linkedin-workspace"><section><div className="sm-card-head"><div><span className="sm-icon linkedin"><Linkedin/></span><div><h3>LinkedIn outreach</h3><p>Short, natural outreach using the same prospect context</p></div></div><a className={!prospect.linkedinUrl?'disabled':''} href={prospect.linkedinUrl||undefined} target="_blank" rel="noreferrer"><ExternalLink/>Open LinkedIn profile</a></div><div className="sm-linkedin-types">{['Connection Request','First Message','Follow-up Message','Custom Message'].map(x=><button className={kind===x?'active':''} key={x} onClick={()=>setKind(x)}>{x}</button>)}</div><textarea value={message} onChange={e=>setMessage(e.target.value)}/><div className="sm-char-count"><span>{message.length} characters</span><strong>{kind==='Connection Request'?'Recommended: under 300 characters':'Keep it easy to scan'}</strong></div><div className="sm-linkedin-actions"><button onClick={()=>{navigator.clipboard.writeText(message);flash('LinkedIn message copied.')}}><Copy/>Copy message</button></div></section><aside><h3><Sparkles/>AI Assistant</h3><label>Tone<select value={tone} onChange={e=>onTone(e.target.value)}>{TONES.map(x=><option key={x}>{x}</option>)}</select></label>{['Make Shorter','Make Natural','Personalize','Improve CTA'].map(x=><button key={x} onClick={()=>revise(x)}><Wand2/>{x}</button>)}<p><AlertCircle/>Messages are copied for manual use. Nothing is sent automatically.</p></aside></div>}
function FileIcon({type}){if(type?.includes('image'))return <Image/>;if(type?.includes('sheet'))return <FileSpreadsheet/>;if(type?.includes('pdf'))return <FileText/>;return <File/>}
function FileItem({file,onRemove}){return <div className="sm-file"><FileIcon type={file.mimeType}/><span><strong>{file.name}</strong><small>{file.type} · {file.size}</small></span>{file.url&&<a href={file.url} target="_blank" rel="noreferrer"><Eye/></a>}{file.url&&<a href={file.url} download={file.name}><Download/></a>}<button onClick={onRemove}><X/></button></div>}
function AISuggestion({suggestion,onClose,onApply}){return <div className="sm-overlay"><div className="sm-dialog sm-ai-review"><header><div><Sparkles/><span>AI suggestion<strong>Review before changing your draft · {suggestion.action}</strong></span></div><button onClick={onClose}><X/></button></header><div className="sm-ai-preview"><label>Suggested subject<strong>{suggestion.subject||'Keep current subject'}</strong></label><article dangerouslySetInnerHTML={{__html:suggestion.body}}/></div><footer><button onClick={onClose}>Discard</button><button onClick={()=>onApply('insert')}>Insert below</button><button onClick={()=>onApply('replace')}>Replace draft</button><button className="primary" onClick={()=>onApply('apply')}>Apply suggestion</button></footer></div></div>}
function Preview({from,to,cc,subject,body,signature,attachments,onClose}){return <div className="sm-overlay"><div className="sm-preview"><header><div><Eye/><span>Email preview<strong>Exactly how the recipient will see it</strong></span></div><button onClick={onClose}><X/></button></header><div className="sm-preview-meta"><div><span>From</span><strong>{from}</strong></div><div><span>To</span><strong>{to.join(', ')}</strong></div>{cc.length>0&&<div><span>CC</span><strong>{cc.join(', ')}</strong></div>}<div><span>Subject</span><strong>{subject}</strong></div></div><article><div dangerouslySetInnerHTML={{__html:body}}/>{signature&&<div className="sm-preview-signature">{signature}</div>}</article>{attachments.length>0&&<div className="sm-preview-files"><span><Paperclip/>{attachments.length} attachment{attachments.length>1?'s':''}</span>{attachments.map(a=><em key={a.id}><FileIcon type={a.mimeType}/>{a.name}</em>)}</div>}<footer><button onClick={onClose}>Close preview</button></footer></div></div>}
function TemplateModal({onClose,onChoose}){return <div className="sm-overlay"><div className="sm-dialog sm-template-dialog"><header><div><FileText/><span>Email templates<strong>Choose a scenario; it remains fully editable</strong></span></div><button onClick={onClose}><X/></button></header><div className="sm-template-list">{TEMPLATES.map(t=><button key={t[0]} onClick={()=>onChoose(t)}><span><strong>{t[0]}</strong><small>{t[1]||'Start with a blank custom draft'}</small></span><ArrowRight/></button>)}</div></div></div>}
function AssetModal({attached,attach,onClose}){const[type,setType]=useState('All'),types=['All',...new Set(LIBRARY.map(a=>a.type))];return <div className="sm-overlay"><div className="sm-dialog sm-asset-dialog"><header><div><Library/><span>Sales asset library<strong>Select relevant documents for this outreach</strong></span></div><button onClick={onClose}><X/></button></header><div className="sm-asset-filter">{types.map(x=><button className={type===x?'active':''} key={x} onClick={()=>setType(x)}>{x}</button>)}</div><div className="sm-modal-assets">{LIBRARY.filter(a=>type==='All'||a.type===type).map(a=><div key={a.id}><FileIcon type={a.mimeType}/><span><strong>{a.name}</strong><small>{a.type} · {a.size}</small></span><button disabled={attached.some(x=>x.id===a.id)} onClick={()=>attach(a)}>{attached.some(x=>x.id===a.id)?'Attached':'Attach'}</button></div>)}</div><footer><button onClick={onClose}>Done</button></footer></div></div>}
function Confirm({prospect,subject,from,attachments,sending,onClose,onSend}){return <div className="sm-overlay"><div className="sm-dialog sm-confirm"><header><div><Send/><span>Send this email?<strong>One final check before delivery</strong></span></div><button onClick={onClose}><X/></button></header><div><dl><dt>Recipient</dt><dd>{prospect.firstName} {prospect.lastName} · {prospect.email}</dd><dt>Subject</dt><dd>{subject}</dd><dt>Sending account</dt><dd>{from}</dd><dt>Attachments</dt><dd>{attachments.length?attachments.map(a=>a.name).join(', '):'None'}</dd></dl><p><CheckCircle2/>Sending updates the prospect status and Outreach Timeline.</p></div><footer><button onClick={onClose}>Cancel</button><button className="primary" onClick={onSend} disabled={sending}>{sending?'Sending…':'Confirm & send'}</button></footer></div></div>}
function Schedule({value,timezone,onTimezone,onChange,onClose,onSchedule}){return <div className="sm-overlay"><div className="sm-dialog sm-schedule"><header><div><CalendarClock/><span>Schedule send<strong>Choose date, time and timezone</strong></span></div><button onClick={onClose}><X/></button></header><div><label>Send date and time<input type="datetime-local" value={value} min={new Date(Date.now()+300000).toISOString().slice(0,16)} onChange={e=>onChange(e.target.value)}/></label><label>Timezone<select value={timezone} onChange={e=>onTimezone(e.target.value)}>{['Asia/Calcutta','Europe/London','America/New_York','America/Los_Angeles','Australia/Sydney','UTC'].map(x=><option key={x}>{x}</option>)}</select></label></div><footer><button onClick={onClose}>Cancel</button><button className="primary" onClick={onSchedule}>Schedule email</button></footer></div></div>}
function Success({prospect,onTimeline,onAnother,onReturn}){return <div className="sm-success"><span><CheckCircle2/></span><h1>Email sent successfully</h1><p>Your message was sent to <strong>{prospect.firstName} {prospect.lastName}</strong>. The status and Outreach Timeline were updated.</p><div><button onClick={onTimeline}>View timeline</button><button onClick={onAnother}>Send another email</button><button className="primary" onClick={onReturn}>Return to prospects</button></div></div>}
